export enum ContactPlatform {
  TELEGRAM = 'TELEGRAM',
  WHATSAPP = 'WHATSAPP',
  INSTAGRAM = 'INSTAGRAM',
  TIKTOK = 'TIKTOK',
  TWITTER = 'TWITTER',
  ONLYFANS = 'ONLYFANS',
  FANSLY = 'FANSLY',
  WEBSITE = 'WEBSITE',
}
