packages:
  - 'packages/*'
  - 'services/*'
  - 'apps/*'
allowBuilds:
  '"': true
  '[': true
  ']': true
  b: true
  d: true
  e: true
  esbuild: true
  i: true
  l: true
  msw: true
  s: true
  sharp: true
  u: true
  unrs-resolver: true
